# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(644, 477)
        Dialog.setStyleSheet("#topLabel\n"
"{\n"
"    font-size: 40 px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(self.centralwidget)
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.topLabel = QtWidgets.QLabel(self.topFrame)
        self.topLabel.setStyleSheet("")
        self.topLabel.setObjectName("topLabel")
        self.horizontalLayout_2.addWidget(self.topLabel)
        self.verticalLayout.addWidget(self.topFrame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.bottomFrame = QtWidgets.QFrame(self.centralwidget)
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrame.setObjectName("bottomFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottomFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.bottomFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.bottomFrame)
        self.horizontalLayout.addWidget(self.centralwidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.topLabel.setText(_translate("Dialog", "There are your tasks:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
