# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'archive_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArchiveWidget(object):
    def setupUi(self, ArchiveWidget):
        ArchiveWidget.setObjectName("ArchiveWidget")
        ArchiveWidget.resize(986, 670)
        ArchiveWidget.setStyleSheet("*\n"
"{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#centralwidget\n"
"{\n"
"    background-color: #FBEEC1;\n"
"}\n"
"\n"
"#leftMenuContainer\n"
"{\n"
"    background-color: #DCDEDF;\n"
"}\n"
"\n"
"#leftSubContainer QPushButton\n"
"{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10 px;\n"
"    border-bottom-left-radius: 10 px;\n"
"}\n"
"\n"
"#leftMenuContainer QPushButton:hover\n"
"{\n"
"    background-color: #BDBBBB;\n"
"}\n"
"\n"
"#mainBottomWidget QLabel\n"
"{\n"
"    font-size: 24 px;\n"
"}\n"
"\n"
"#mainBottomWidget QTextBrowser\n"
"{\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QCalendarWidget\n"
"{\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(ArchiveWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralwidget = QtWidgets.QWidget(ArchiveWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.leftSubContainer = QtWidgets.QWidget(self.leftMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftSubContainer.sizePolicy().hasHeightForWidth())
        self.leftSubContainer.setSizePolicy(sizePolicy)
        self.leftSubContainer.setObjectName("leftSubContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftSubContainer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.leftTopFrame = QtWidgets.QFrame(self.leftSubContainer)
        self.leftTopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftTopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftTopFrame.setObjectName("leftTopFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.leftTopFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBtn = QtWidgets.QPushButton(self.leftTopFrame)
        self.menuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/6498732_application_list_menu_mobile_smartphone_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon)
        self.menuBtn.setIconSize(QtCore.QSize(24, 24))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_2.addWidget(self.menuBtn)
        self.verticalLayout_4.addWidget(self.leftTopFrame, 0, QtCore.Qt.AlignTop)
        self.leftCentralFrame = QtWidgets.QFrame(self.leftSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftCentralFrame.sizePolicy().hasHeightForWidth())
        self.leftCentralFrame.setSizePolicy(sizePolicy)
        self.leftCentralFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftCentralFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftCentralFrame.setObjectName("leftCentralFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftCentralFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeBtn = QtWidgets.QPushButton(self.leftCentralFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-home-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon1)
        self.homeBtn.setIconSize(QtCore.QSize(24, 24))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_3.addWidget(self.homeBtn)
        self.archiveBtn = QtWidgets.QPushButton(self.leftCentralFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-news-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.archiveBtn.setIcon(icon2)
        self.archiveBtn.setIconSize(QtCore.QSize(24, 24))
        self.archiveBtn.setObjectName("archiveBtn")
        self.verticalLayout_3.addWidget(self.archiveBtn)
        self.dataAnalysisBtn = QtWidgets.QPushButton(self.leftCentralFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/7549001_user_interface_graph_chart_business_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataAnalysisBtn.setIcon(icon3)
        self.dataAnalysisBtn.setIconSize(QtCore.QSize(24, 24))
        self.dataAnalysisBtn.setObjectName("dataAnalysisBtn")
        self.verticalLayout_3.addWidget(self.dataAnalysisBtn)
        self.pushButton = QtWidgets.QPushButton(self.leftCentralFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-news-64 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.leftCentralFrame, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.leftBottomFrame = QtWidgets.QFrame(self.leftSubContainer)
        self.leftBottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBottomFrame.setObjectName("leftBottomFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.leftBottomFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.settingsBtn = QtWidgets.QPushButton(self.leftBottomFrame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-settings-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon5)
        self.settingsBtn.setIconSize(QtCore.QSize(24, 24))
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_5.addWidget(self.settingsBtn)
        self.reportBtn = QtWidgets.QPushButton(self.leftBottomFrame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/7324045_ui_interface_email_mail_message_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportBtn.setIcon(icon6)
        self.reportBtn.setIconSize(QtCore.QSize(24, 24))
        self.reportBtn.setObjectName("reportBtn")
        self.verticalLayout_5.addWidget(self.reportBtn)
        self.verticalLayout_4.addWidget(self.leftBottomFrame)
        self.verticalLayout_2.addWidget(self.leftSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.leftMenuContainer)
        self.mainMenuContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainMenuContainer.sizePolicy().hasHeightForWidth())
        self.mainMenuContainer.setSizePolicy(sizePolicy)
        self.mainMenuContainer.setObjectName("mainMenuContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mainMenuContainer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mainSubContainer = QtWidgets.QWidget(self.mainMenuContainer)
        self.mainSubContainer.setObjectName("mainSubContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mainSubContainer)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_6.setSpacing(11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainTopWidget = QtWidgets.QWidget(self.mainSubContainer)
        self.mainTopWidget.setObjectName("mainTopWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainTopWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.mainTopWidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_7.addWidget(self.calendarWidget)
        self.verticalLayout_6.addWidget(self.mainTopWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.mainBottomWidget = QtWidgets.QWidget(self.mainSubContainer)
        self.mainBottomWidget.setObjectName("mainBottomWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mainBottomWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.subTopWidget = QtWidgets.QWidget(self.mainBottomWidget)
        self.subTopWidget.setObjectName("subTopWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.subTopWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tasksLabel = QtWidgets.QLabel(self.subTopWidget)
        self.tasksLabel.setObjectName("tasksLabel")
        self.horizontalLayout_4.addWidget(self.tasksLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.achLabel = QtWidgets.QLabel(self.subTopWidget)
        self.achLabel.setObjectName("achLabel")
        self.horizontalLayout_4.addWidget(self.achLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_8.addWidget(self.subTopWidget)
        self.subBottomWidget = QtWidgets.QWidget(self.mainBottomWidget)
        self.subBottomWidget.setObjectName("subBottomWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.subBottomWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tasksTextBrowser = QtWidgets.QTextBrowser(self.subBottomWidget)
        self.tasksTextBrowser.setObjectName("tasksTextBrowser")
        self.horizontalLayout_5.addWidget(self.tasksTextBrowser)
        self.achTextBrowser = QtWidgets.QTextBrowser(self.subBottomWidget)
        self.achTextBrowser.setObjectName("achTextBrowser")
        self.horizontalLayout_5.addWidget(self.achTextBrowser)
        self.verticalLayout_8.addWidget(self.subBottomWidget)
        self.verticalLayout_6.addWidget(self.mainBottomWidget)
        self.horizontalLayout_3.addWidget(self.mainSubContainer)
        self.horizontalLayout.addWidget(self.mainMenuContainer)
        self.verticalLayout.addWidget(self.centralwidget)

        self.retranslateUi(ArchiveWidget)
        QtCore.QMetaObject.connectSlotsByName(ArchiveWidget)

    def retranslateUi(self, ArchiveWidget):
        _translate = QtCore.QCoreApplication.translate
        ArchiveWidget.setWindowTitle(_translate("ArchiveWidget", "Form"))
        self.menuBtn.setToolTip(_translate("ArchiveWidget", "Menu"))
        self.homeBtn.setToolTip(_translate("ArchiveWidget", "Home"))
        self.homeBtn.setText(_translate("ArchiveWidget", "Home"))
        self.archiveBtn.setToolTip(_translate("ArchiveWidget", "Archive"))
        self.archiveBtn.setText(_translate("ArchiveWidget", "Archive data"))
        self.dataAnalysisBtn.setToolTip(_translate("ArchiveWidget", "Data Analysis"))
        self.dataAnalysisBtn.setText(_translate("ArchiveWidget", "Data Analysis"))
        self.pushButton.setText(_translate("ArchiveWidget", "Helpful articles"))
        self.settingsBtn.setToolTip(_translate("ArchiveWidget", "Settings"))
        self.settingsBtn.setText(_translate("ArchiveWidget", "Settings"))
        self.reportBtn.setToolTip(_translate("ArchiveWidget", "Report"))
        self.reportBtn.setText(_translate("ArchiveWidget", "Report"))
        self.tasksLabel.setText(_translate("ArchiveWidget", "Tasks:"))
        self.achLabel.setText(_translate("ArchiveWidget", "Achievements:"))
import main_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ArchiveWidget = QtWidgets.QWidget()
    ui = Ui_ArchiveWidget()
    ui.setupUi(ArchiveWidget)
    ArchiveWidget.show()
    sys.exit(app.exec_())
