# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report_error_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 307)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainWidget = QtWidgets.QWidget(Dialog)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleFrame = QtWidgets.QFrame(self.mainWidget)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(self.titleFrame)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        self.verticalLayout_2.addWidget(self.titleFrame)
        self.idFrame = QtWidgets.QFrame(self.mainWidget)
        self.idFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.idFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.idFrame.setObjectName("idFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.idFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.idLabel = QtWidgets.QLabel(self.idFrame)
        self.idLabel.setObjectName("idLabel")
        self.horizontalLayout_2.addWidget(self.idLabel)
        self.verticalLayout_2.addWidget(self.idFrame)
        self.errorFrame = QtWidgets.QFrame(self.mainWidget)
        self.errorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.errorFrame.setObjectName("errorFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.errorFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.errorLabel = QtWidgets.QLabel(self.errorFrame)
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout_3.addWidget(self.errorLabel)
        self.verticalLayout_2.addWidget(self.errorFrame)
        self.shareFrame = QtWidgets.QFrame(self.mainWidget)
        self.shareFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shareFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shareFrame.setObjectName("shareFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.shareFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.shareLabel = QtWidgets.QLabel(self.shareFrame)
        self.shareLabel.setObjectName("shareLabel")
        self.verticalLayout_3.addWidget(self.shareLabel)
        self.shareTextEdit = QtWidgets.QTextEdit(self.shareFrame)
        self.shareTextEdit.setObjectName("shareTextEdit")
        self.verticalLayout_3.addWidget(self.shareTextEdit)
        self.verticalLayout_2.addWidget(self.shareFrame)
        self.verticalLayout.addWidget(self.mainWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleLabel.setText(_translate("Dialog", "Some error was occured. Do you want to report an issue?"))
        self.idLabel.setText(_translate("Dialog", "Error id: "))
        self.errorLabel.setText(_translate("Dialog", "Text of error:"))
        self.shareLabel.setText(_translate("Dialog", "Share your issue:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
