# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(600, 600))
        Form.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWhatsThis("")
        Form.setStyleSheet("QLabel{\n"
"    font-family: \"Verdana\", serif;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    width: 250px;\n"
"    height: 35px;\n"
"    background-color: #D9D9D9;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: #FBE8A6;\n"
"    width: 250px;\n"
"    height: 35px;\n"
"    border: 1px solid;\n"
"    border-radius: 3px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    width: 250px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"#closeTabWidget QPushButton{\n"
"    background-color: #F4976C;\n"
"    width: 75px;\n"
"    height: 20px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"#closeTabWidget QPushButton:hover{\n"
"    background-color: #C5C6C7;\n"
"}\n"
"\n"
"#logInWidget QPushButton:hover{\n"
"    background-color: #D2FDFF;\n"
"}\n"
"\n"
"#forgotPasswordWidget QPushButton:hover{\n"
"    background-color: #F4976C;\n"
"}\n"
"\n"
"#createAccountBtn:hover{\n"
"    background-color: #D2FDFF;\n"
"}\n"
"\n"
"#logInWidget{\n"
"    background-color: #F4976C;\n"
"}\n"
"\n"
"#signUpWidget{\n"
"    background-color: #F4976C;\n"
"}\n"
"\n"
"#closeTabWidget {\n"
"    background-color: #F4976C;\n"
"}\n"
"\n"
"#forgotPasswordBtn:hover{\n"
"    background-color: #F4976C;\n"
"}\n"
"\n"
"#forgotPasswordBtn{\n"
"    background-color: #F4976C;\n"
"    border: 0px;\n"
"    color: #303C6C;\n"
"}\n"
"\n"
"#welcomeBackLabel{\n"
"    font-size: 36px;\n"
"}\n"
"\n"
"#logInFancyLabel{\n"
"    text-align: center;\n"
"}\n"
"\n"
"#nameOfAppLabel{\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#joinPersonalTrackerLabel{\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.closeTabWidget = QtWidgets.QWidget(Form)
        self.closeTabWidget.setObjectName("closeTabWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.closeTabWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(self.closeTabWidget)
        self.icon.setMinimumSize(QtCore.QSize(25, 25))
        self.icon.setMaximumSize(QtCore.QSize(25, 25))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/icons/tiny_icon.png"))
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.nameOfAppLabel = QtWidgets.QLabel(self.closeTabWidget)
        self.nameOfAppLabel.setObjectName("nameOfAppLabel")
        self.horizontalLayout.addWidget(self.nameOfAppLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.collapseWindowBtn = QtWidgets.QPushButton(self.closeTabWidget)
        self.collapseWindowBtn.setMinimumSize(QtCore.QSize(40, 20))
        self.collapseWindowBtn.setMaximumSize(QtCore.QSize(40, 20))
        self.collapseWindowBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/collapse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.collapseWindowBtn.setIcon(icon1)
        self.collapseWindowBtn.setObjectName("collapseWindowBtn")
        self.horizontalLayout.addWidget(self.collapseWindowBtn)
        self.closeWindowBtn = QtWidgets.QPushButton(self.closeTabWidget)
        self.closeWindowBtn.setMinimumSize(QtCore.QSize(40, 20))
        self.closeWindowBtn.setMaximumSize(QtCore.QSize(40, 20))
        self.closeWindowBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeWindowBtn.setIcon(icon2)
        self.closeWindowBtn.setObjectName("closeWindowBtn")
        self.horizontalLayout.addWidget(self.closeWindowBtn)
        self.verticalLayout_9.addWidget(self.closeTabWidget)
        self.mainBody = QtWidgets.QStackedWidget(Form)
        self.mainBody.setObjectName("mainBody")
        self.logInWidget = QtWidgets.QWidget()
        self.logInWidget.setObjectName("logInWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.logInWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftLogInWidget = QtWidgets.QWidget(self.logInWidget)
        self.leftLogInWidget.setMinimumSize(QtCore.QSize(330, 0))
        self.leftLogInWidget.setMaximumSize(QtCore.QSize(330, 16777215))
        self.leftLogInWidget.setObjectName("leftLogInWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftLogInWidget)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.welcomeLabelsWidget = QtWidgets.QWidget(self.leftLogInWidget)
        self.welcomeLabelsWidget.setMinimumSize(QtCore.QSize(306, 140))
        self.welcomeLabelsWidget.setMaximumSize(QtCore.QSize(306, 140))
        self.welcomeLabelsWidget.setObjectName("welcomeLabelsWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.welcomeLabelsWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.welcomeBackLabel = QtWidgets.QLabel(self.welcomeLabelsWidget)
        self.welcomeBackLabel.setObjectName("welcomeBackLabel")
        self.verticalLayout_4.addWidget(self.welcomeBackLabel)
        self.logInFancyLabel = QtWidgets.QLabel(self.welcomeLabelsWidget)
        self.logInFancyLabel.setMinimumSize(QtCore.QSize(290, 75))
        self.logInFancyLabel.setMaximumSize(QtCore.QSize(290, 75))
        self.logInFancyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.logInFancyLabel.setWordWrap(True)
        self.logInFancyLabel.setObjectName("logInFancyLabel")
        self.verticalLayout_4.addWidget(self.logInFancyLabel)
        self.verticalLayout_3.addWidget(self.welcomeLabelsWidget)
        self.authorizationWidget = QtWidgets.QWidget(self.leftLogInWidget)
        self.authorizationWidget.setMinimumSize(QtCore.QSize(290, 403))
        self.authorizationWidget.setMaximumSize(QtCore.QSize(290, 403))
        self.authorizationWidget.setObjectName("authorizationWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.authorizationWidget)
        self.verticalLayout_6.setContentsMargins(11, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.loginAndPasswordWidget = QtWidgets.QWidget(self.authorizationWidget)
        self.loginAndPasswordWidget.setObjectName("loginAndPasswordWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.loginAndPasswordWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logInLabel = QtWidgets.QLabel(self.loginAndPasswordWidget)
        self.logInLabel.setObjectName("logInLabel")
        self.verticalLayout_5.addWidget(self.logInLabel)
        self.logInLineEdit = QtWidgets.QLineEdit(self.loginAndPasswordWidget)
        self.logInLineEdit.setMinimumSize(QtCore.QSize(250, 35))
        self.logInLineEdit.setMaximumSize(QtCore.QSize(250, 35))
        self.logInLineEdit.setStyleSheet("border-radius: 14.5;")
        self.logInLineEdit.setObjectName("logInLineEdit")
        self.verticalLayout_5.addWidget(self.logInLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.loginAndPasswordWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout_5.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.loginAndPasswordWidget)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(250, 35))
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(250, 35))
        self.passwordLineEdit.setStyleSheet("border-radius: 14.5;")
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout_5.addWidget(self.passwordLineEdit)
        self.verticalLayout_6.addWidget(self.loginAndPasswordWidget)
        self.forgotPasswordWidget = QtWidgets.QWidget(self.authorizationWidget)
        self.forgotPasswordWidget.setObjectName("forgotPasswordWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.forgotPasswordWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.forgotPasswordBtn = QtWidgets.QPushButton(self.forgotPasswordWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forgotPasswordBtn.sizePolicy().hasHeightForWidth())
        self.forgotPasswordBtn.setSizePolicy(sizePolicy)
        self.forgotPasswordBtn.setMinimumSize(QtCore.QSize(100, 19))
        self.forgotPasswordBtn.setMaximumSize(QtCore.QSize(100, 19))
        self.forgotPasswordBtn.setObjectName("forgotPasswordBtn")
        self.horizontalLayout_3.addWidget(self.forgotPasswordBtn)
        self.verticalLayout_6.addWidget(self.forgotPasswordWidget, 0, QtCore.Qt.AlignRight)
        spacerItem3 = QtWidgets.QSpacerItem(100, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem3)
        self.signInBtn = QtWidgets.QPushButton(self.authorizationWidget)
        self.signInBtn.setMinimumSize(QtCore.QSize(250, 35))
        self.signInBtn.setMaximumSize(QtCore.QSize(250, 35))
        self.signInBtn.setStyleSheet("border-radius:17;")
        self.signInBtn.setObjectName("signInBtn")
        self.verticalLayout_6.addWidget(self.signInBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.authorizationWidget, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.leftLogInWidget)
        self.rightLogInWidget = QtWidgets.QWidget(self.logInWidget)
        self.rightLogInWidget.setObjectName("rightLogInWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightLogInWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.capybaraImage = QtWidgets.QLabel(self.rightLogInWidget)
        self.capybaraImage.setMinimumSize(QtCore.QSize(245, 373))
        self.capybaraImage.setMaximumSize(QtCore.QSize(245, 373))
        self.capybaraImage.setText("")
        self.capybaraImage.setPixmap(QtGui.QPixmap(":/newPrefix/images/login_capybara.png"))
        self.capybaraImage.setObjectName("capybaraImage")
        self.verticalLayout_2.addWidget(self.capybaraImage)
        self.newUserBtn = QtWidgets.QPushButton(self.rightLogInWidget)
        self.newUserBtn.setMinimumSize(QtCore.QSize(250, 35))
        self.newUserBtn.setMaximumSize(QtCore.QSize(250, 35))
        self.newUserBtn.setStyleSheet("border-radius:17;")
        self.newUserBtn.setObjectName("newUserBtn")
        self.verticalLayout_2.addWidget(self.newUserBtn)
        self.horizontalLayout_2.addWidget(self.rightLogInWidget)
        self.mainBody.addWidget(self.logInWidget)
        self.signUpWidget = QtWidgets.QWidget()
        self.signUpWidget.setObjectName("signUpWidget")
        self.joinPersonalTrackerWidget = QtWidgets.QWidget(self.signUpWidget)
        self.joinPersonalTrackerWidget.setEnabled(True)
        self.joinPersonalTrackerWidget.setGeometry(QtCore.QRect(0, -1, 600, 91))
        self.joinPersonalTrackerWidget.setMinimumSize(QtCore.QSize(600, 91))
        self.joinPersonalTrackerWidget.setMaximumSize(QtCore.QSize(600, 91))
        self.joinPersonalTrackerWidget.setObjectName("joinPersonalTrackerWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.joinPersonalTrackerWidget)
        self.verticalLayout_8.setContentsMargins(83, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.joinPersonalTrackerLabel = QtWidgets.QLabel(self.joinPersonalTrackerWidget)
        self.joinPersonalTrackerLabel.setMinimumSize(QtCore.QSize(431, 41))
        self.joinPersonalTrackerLabel.setMaximumSize(QtCore.QSize(431, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana,serif")
        font.setPointSize(-1)
        self.joinPersonalTrackerLabel.setFont(font)
        self.joinPersonalTrackerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.joinPersonalTrackerLabel.setObjectName("joinPersonalTrackerLabel")
        self.verticalLayout_8.addWidget(self.joinPersonalTrackerLabel)
        self.newUserWidget = QtWidgets.QWidget(self.signUpWidget)
        self.newUserWidget.setGeometry(QtCore.QRect(0, 90, 601, 281))
        self.newUserWidget.setObjectName("newUserWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.newUserWidget)
        self.verticalLayout_7.setContentsMargins(52, 0, 52, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.usernameLabel = QtWidgets.QLabel(self.newUserWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout_7.addWidget(self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.newUserWidget)
        self.usernameLineEdit.setEnabled(True)
        self.usernameLineEdit.setMinimumSize(QtCore.QSize(501, 38))
        self.usernameLineEdit.setMaximumSize(QtCore.QSize(501, 38))
        self.usernameLineEdit.setStyleSheet("border-radius: 19;")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout_7.addWidget(self.usernameLineEdit)
        self.newPasswordLabel = QtWidgets.QLabel(self.newUserWidget)
        self.newPasswordLabel.setObjectName("newPasswordLabel")
        self.verticalLayout_7.addWidget(self.newPasswordLabel)
        self.newPasswordLineEdit = QtWidgets.QLineEdit(self.newUserWidget)
        self.newPasswordLineEdit.setMinimumSize(QtCore.QSize(501, 38))
        self.newPasswordLineEdit.setMaximumSize(QtCore.QSize(501, 38))
        self.newPasswordLineEdit.setStyleSheet("border-radius: 19;")
        self.newPasswordLineEdit.setObjectName("newPasswordLineEdit")
        self.verticalLayout_7.addWidget(self.newPasswordLineEdit)
        self.repeatPasswordLabel = QtWidgets.QLabel(self.newUserWidget)
        self.repeatPasswordLabel.setObjectName("repeatPasswordLabel")
        self.verticalLayout_7.addWidget(self.repeatPasswordLabel)
        self.repeatPasswordLineEdit = QtWidgets.QLineEdit(self.newUserWidget)
        self.repeatPasswordLineEdit.setMinimumSize(QtCore.QSize(0, 38))
        self.repeatPasswordLineEdit.setMaximumSize(QtCore.QSize(16777215, 38))
        self.repeatPasswordLineEdit.setStyleSheet("border-radius: 19;")
        self.repeatPasswordLineEdit.setObjectName("repeatPasswordLineEdit")
        self.verticalLayout_7.addWidget(self.repeatPasswordLineEdit)
        self.createUserCapybaraWidget = QtWidgets.QWidget(self.signUpWidget)
        self.createUserCapybaraWidget.setGeometry(QtCore.QRect(0, 370, 311, 194))
        self.createUserCapybaraWidget.setMinimumSize(QtCore.QSize(311, 194))
        self.createUserCapybaraWidget.setMaximumSize(QtCore.QSize(311, 194))
        self.createUserCapybaraWidget.setObjectName("createUserCapybaraWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.createUserCapybaraWidget)
        self.horizontalLayout_4.setContentsMargins(52, 43, 0, 113)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.createAccountBtn = QtWidgets.QPushButton(self.createUserCapybaraWidget)
        self.createAccountBtn.setMinimumSize(QtCore.QSize(250, 38))
        self.createAccountBtn.setMaximumSize(QtCore.QSize(250, 38))
        self.createAccountBtn.setStyleSheet("border-radius: 19;")
        self.createAccountBtn.setObjectName("createAccountBtn")
        self.horizontalLayout_4.addWidget(self.createAccountBtn)
        self.capybaraCarrotWidget = QtWidgets.QWidget(self.signUpWidget)
        self.capybaraCarrotWidget.setGeometry(QtCore.QRect(310, 370, 291, 194))
        self.capybaraCarrotWidget.setObjectName("capybaraCarrotWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.capybaraCarrotWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.capybaraCarrot = QtWidgets.QLabel(self.capybaraCarrotWidget)
        self.capybaraCarrot.setMinimumSize(QtCore.QSize(175, 170))
        self.capybaraCarrot.setMaximumSize(QtCore.QSize(175, 170))
        self.capybaraCarrot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.capybaraCarrot.setStyleSheet("background-image: url(:/newPrefix/OIG (2).jpeg);")
        self.capybaraCarrot.setText("")
        self.capybaraCarrot.setPixmap(QtGui.QPixmap(":/newPrefix/images/OIG (2).jpeg"))
        self.capybaraCarrot.setScaledContents(True)
        self.capybaraCarrot.setObjectName("capybaraCarrot")
        self.horizontalLayout_5.addWidget(self.capybaraCarrot)
        spacerItem6 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.mainBody.addWidget(self.signUpWidget)
        self.verticalLayout_9.addWidget(self.mainBody)

        self.retranslateUi(Form)
        self.mainBody.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Log In to account"))
        self.nameOfAppLabel.setText(_translate("Form", "Personal Tracker"))
        self.welcomeBackLabel.setText(_translate("Form", "Welcome back"))
        self.logInFancyLabel.setText(_translate("Form", "Log in to the system and track your progress with us!"))
        self.logInLabel.setText(_translate("Form", "Login:"))
        self.passwordLabel.setText(_translate("Form", "Password:"))
        self.forgotPasswordBtn.setText(_translate("Form", "Forgot password?"))
        self.signInBtn.setText(_translate("Form", "Sign in"))
        self.newUserBtn.setText(_translate("Form", "I\'m a new user"))
        self.joinPersonalTrackerLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:20pt;\">Join Personal Tracker</span></p></body></html>"))
        self.usernameLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Username:</span></p></body></html>"))
        self.newPasswordLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Password:</span></p></body></html>"))
        self.repeatPasswordLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Repeat Password:</span></p></body></html>"))
        self.createAccountBtn.setText(_translate("Form", "Create account"))
import main_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
